selenium-hub:
  image: selenium/hub
  ports:
    - "4444:4444"
selenium-firefox:
  image: selenium/node-firefox
  links:
    - selenium-hub
  environment:
    - "HUB_PORT_4444_TCP_ADDR=selenium-hub"
    - "HUB_PORT_4444_TCP_PORT=4444"
selenium-chrome:
  image: selenium/node-chrome
  environment:
    - "HUB_PORT_4444_TCP_ADDR=selenium-hub"
    - "HUB_PORT_4444_TCP_PORT=4444"
  links:
    - selenium-hub
