selenium-hub:
  image: selenium/hub
  ports:
    - "4444:4444"
selenium-firefox:
  image: selenium/node-firefox
  links:
    - selenium-hub:hub
selenium-chrome:
  image: selenium/node-chrome
  links:
    - selenium-hub:hub
